### ISSUE TITLE
think of a cooler name for this

### ISSUE THREAD

**Issue by twillis** [team-apollo/apollo#11]
@ttrucco doesn't like spazzer. I guess there's a branding discussion somewhere in the future.

**Comment by ttrucco** [comment]
BURN!

**Comment by ttrucco** [comment]
Or, the Roman god of fire, Vulcan :D

**Comment by justfill22** [comment]
Too badd "Good Apollo, I'm Burning Star IV, Volume One: From Fear Through the Eyes of Madness" is already taken, cause that would totally rock as a name for a browser based music player.

How about Apollo Music Player, which 1. retains the uber cool Apollo thingy, 2. actually says what it does in the title of the product 3. has a cool acronyn AMP.
