### ISSUE TITLE
what settings page

### ISSUE THREAD

**Issue by justfill22** [team-apollo/apollo#26]
The doc says

> scanning your directories(mounts)
> Update: in the browser you can now do this from the settings page, ugly as it may be

However, I don't see anywhere in the doc how to get to the settings page and I don't see a link to the settings page from inside the browser.

**Comment by twillis** [comment]
it's over on the right, the gear below the magnifying glass. 

![screen shot 2015-02-21 at 10 28 14 am](https://cloud.githubusercontent.com/assets/183699/6314634/6f09bf96-b9b4-11e4-919e-a9824a85967e.png)

**Comment by twillis** [comment]
if you dont see the gear that means fontawesome isn't installed, and that's a javascript thing.

 https://github.com/team-apollo/apollo#setting-up-js-libsreactjsfontawesome

**Comment by justfill22** [comment]
installed node.js and bower.  was able to get up and running w/ gear icon
and had it successfully read music directory

On Sat, Feb 21, 2015 at 7:33 AM, Tom Willis <notifications@github.com>
wrote:

> if you dont see the gear that means fontawesome isn't installed, and
> that's a javascript thing.
>
> https://github.com/team-apollo/apollo#setting-up-js-libsreactjsfontawesome
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/team-apollo/apollo/issues/26#issuecomment-75376724>.
>



-- 
----------------------------------------------------------
   Phil Jones ~ justfill22@gmail.com
----------------------------------------------------------

**Comment by twillis** [comment]
allrighty glad to hear it.
